# Generated by Django 4.0.3 on 2022-03-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Music',
        ),
    ]
